name: First Challenge with Job dependencies
on: push

jobs:
  job-01:
    name: First Job - Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Current date
      run: date
    - name: Greetings
      run: echo "Hello world"
  job-02:
    name: Second Job - Windows
    runs-on: windows-latest
    steps:
    - name: Current date
      run: date
    - name: Greetings
      run: echo "Hello world"
  job-03:
    name: Third Job - MacOs
    runs-on: macos-latest
    steps:
    - name: Current date
      run: date
    - name: Greetings
      run: echo "Hello world"  
  job-04:
    name: Fourth Job - Ubuntu
    runs-on: ubuntu-18.04
    needs: [job-01, job-02, job-03]
    steps:
    - name: Current date
      run: date
    - name: Greetings
      run: echo "Hello world from Ubuntu 18.04"  